"""followers

Revision ID: 028a565b9a7c
Revises: 6a3935495154
Create Date: 2024-03-19 21:04:58.122846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028a565b9a7c'
down_revision = '6a3935495154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
